name: shizuku_api
description:  "A Flutter Plugin that gives access to shizuku api."
version: 1.2.2
homepage: https://github.com/santhosh-D-subramani/Shizuku-Plugin/


environment:
  sdk: ^3.9.2
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  plugin:
    platforms:
      android:
        package: com.santhoshDsubramani.shizuku_api
        pluginClass: ShizukuApiPlugin
