name: shizuku_api
description:  "A Flutter Plugin that gives access to shizuku api."
version: 1.0.1
homepage: https://github.com/santhosh-D-subramani/Shizuku-Plugin/
environment:
  sdk: ^3.5.3
  flutter: '>=3.3.0'
dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  plugin:
    platforms:
      android:
        package: com.santhoshDsubramani.shizuku_api
        pluginClass: ShizukuApiPlugin
